### PR TITLE
Add missing sp_typeinfo_.hpp includes

### PR DESCRIPTION
**Pull request by MarcelRaad**
Some of these are included indirectly, but others are not.
Broken in commit e306b30dcf0.

### CODE REVIEW

**Comment by MarcelRaad** [comment]
The clang-win AppVeyor failures look unrelated to me.

**Comment by pdimov** [comment]
How was this "broken"? The patch didn't change or remove any includes, and there were no failures.

**Comment by MarcelRaad** [comment]
What I get for `#include <boost/shared_array.hpp>` is:

```
In file included from [...]/boost/shared_array.hpp:17:
[...]/boost/smart_ptr/shared_array.hpp:228:50: error: no type named 'sp_typeinfo_' in namespace 'boost::detail'; did you mean 'sp_typeinfo'?
    void * _internal_get_deleter( boost::detail::sp_typeinfo_ const & ti ) const BOOST_SP_NOEXCEPT
                                  ~~~~~~~~~~~~~~~^
```

**Comment by pdimov** [comment]
Thanks, I'll take a look to see what changed there.

**Comment by pdimov** [comment]
Can you please trace the includes? I don't get the error; the include chain is supposed to go shared_array.hpp -> detail/shared_count.hpp -> detail/sp_counted_base.hpp -> detail/sp_counted_base_{impl}.hpp -> detail/sp_typeinfo_.hpp.

**Comment by pdimov** [comment]
As far as I can see, all sp_counted_base_{impl}.hpp files include detail/sp_typeinfo_.hpp, so there must be something else going on here.

**Comment by MarcelRaad** [comment]
I only noticed this on a build machine I don't have direct access to. Good idea to trace the includes - it looks like this is not Boost's fault at all. A precompiled header didn't get recompiled automatically after the Boost update from 1.70 to 1.71, which included the 1.70 version of boost/thread/mutex.hpp, which ended up including the 1.70 version of sp_counted_base_clang.hpp through shared_ptr.hpp, which was fixed in the commit mentioned above. Sorry for the false alarm!

**Comment by pdimov** [comment]
Glad we sorted this out. :-)
